using System.Text.Json;using HealthTracker.Api.Contracts;using HealthTracker.Api.Data;using HealthTracker.Api.Models;using Microsoft.EntityFrameworkCore;namespace HealthTracker.Api.Services;
public interface IDoseService{Task<List<DoseResponse>>Get(Guid userId,DateOnly date,Guid? patientId);Task<DoseResponse>Take(Guid userId,Guid id);Task<DoseResponse>Skip(Guid userId,Guid id,string reason);Task<DoseResponse>Reschedule(Guid userId,Guid id,DateOnly date);Task<DoseResponse>Undo(Guid userId,Guid id);}
public class DoseService(AppDbContext db):IDoseService{
 public async Task<List<DoseResponse>>Get(Guid uid,DateOnly date,Guid? patientId){var ids=await AccessibleUserIds(uid);var p=patientId.HasValue?await db.Patients.SingleOrDefaultAsync(x=>x.Id==patientId.Value):await db.Patients.SingleOrDefaultAsync(x=>x.UserId==uid);if(p is null)throw new KeyNotFoundException("Patient not found.");if(!ids.Contains(p.UserId))throw new UnauthorizedAccessException("You do not have access to this patient.");var owner=await db.Users.FindAsync(p.UserId);var tz=Zone(owner?.TimeZoneId??"Asia/Kolkata");var meds=await db.Medicines.Where(x=>x.PatientId==p.Id).ToListAsync();var medIds=meds.Select(x=>x.Id).ToList();var events=await db.DoseEvents.Where(x=>x.PatientId==p.Id&&x.Date==date&&medIds.Contains(x.MedicineId)).ToListAsync();var byKey=events.ToDictionary(x=>$"{x.MedicineId}:{x.Time}");var missing=new List<DoseEvent>();var result=new List<DoseResponse>();foreach(var m in meds){if(!Occurs(m,date))continue;foreach(var time in (JsonSerializer.Deserialize<List<string>>(m.TimesJson)??[]).Distinct()){if(!byKey.TryGetValue($"{m.Id}:{time}",out var d)){d=new DoseEvent{PatientId=p.Id,MedicineId=m.Id,Date=date,Time=time};missing.Add(d);byKey[$"{m.Id}:{time}"]=d;}if(date==DateOnly.FromDateTime(TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow,tz).DateTime))ApplyCurrentState(d,tz);result.Add(Map(d,m,p));}}if(missing.Count>0)db.DoseEvents.AddRange(missing);await db.SaveChangesAsync();return result.OrderBy(x=>x.Time).ToList();}
 public async Task<DoseResponse>Take(Guid uid,Guid id){var x=await Event(uid,id);var now=DateTimeOffset.UtcNow;var scheduled=ScheduledAt(x.Dose,Zone(x.OwnerTimeZone));if(now<scheduled)throw new InvalidOperationException("This dose cannot be taken before its scheduled time.");if(now>scheduled.AddHours(1))throw new InvalidOperationException("This dose is locked. It can only be marked taken within 1 hour of the scheduled time.");if(x.Medicine.SupplyCount<1)throw new InvalidOperationException("No supply remains for this medicine.");if(x.Dose.Status=="taken")return Map(x.Dose,x.Medicine,x.Patient);x.Dose.Status="taken";x.Dose.TakenAt=now;x.Dose.ActionedByUserId=uid;x.Medicine.SupplyCount--;await db.SaveChangesAsync();return Map(x.Dose,x.Medicine,x.Patient);}
 public async Task<DoseResponse>Skip(Guid uid,Guid id,string reason){var x=await Event(uid,id);var now=DateTimeOffset.UtcNow;var scheduled=ScheduledAt(x.Dose,Zone(x.OwnerTimeZone));if(now<scheduled)throw new InvalidOperationException("This dose cannot be skipped before its scheduled time.");if(now>scheduled.AddHours(1))throw new InvalidOperationException("This dose is locked after 1 hour.");x.Dose.Status="skipped";x.Dose.SkipReason=string.IsNullOrWhiteSpace(reason)?"Skipped by user":reason.Trim();x.Dose.ActionedByUserId=uid;await db.SaveChangesAsync();return Map(x.Dose,x.Medicine,x.Patient);}
 public async Task<DoseResponse>Reschedule(Guid uid,Guid id,DateOnly date){var x=await Event(uid,id);x.Dose.Status="rescheduled";x.Dose.RescheduleTo=date;x.Dose.ActionedByUserId=uid;await db.SaveChangesAsync();return Map(x.Dose,x.Medicine,x.Patient);}
 public async Task<DoseResponse>Undo(Guid uid,Guid id){var x=await Event(uid,id);var now=DateTimeOffset.UtcNow;var scheduled=ScheduledAt(x.Dose,Zone(x.OwnerTimeZone));if(now>scheduled.AddHours(1))throw new InvalidOperationException("This dose is locked after 1 hour.");x.Dose.Status="pending";x.Dose.TakenAt=null;x.Dose.SkipReason=null;x.Dose.RescheduleTo=null;x.Dose.MissedAt=null;x.Dose.ActionedByUserId=uid;await db.SaveChangesAsync();return Map(x.Dose,x.Medicine,x.Patient);}
 void ApplyCurrentState(DoseEvent d,TimeZoneInfo tz){if(d.Status=="pending"&&DateTimeOffset.UtcNow>ScheduledAt(d,tz)){d.Status="missed";d.MissedAt??=DateTimeOffset.UtcNow;}}
 async Task<(DoseEvent Dose,Medicine Medicine,Patient Patient,string OwnerTimeZone)>Event(Guid uid,Guid id){var d=await db.DoseEvents.SingleOrDefaultAsync(x=>x.Id==id)??throw new KeyNotFoundException("Dose not found.");var p=await db.Patients.SingleOrDefaultAsync(x=>x.Id==d.PatientId)??throw new KeyNotFoundException("Patient not found.");var ids=await AccessibleUserIds(uid);if(!ids.Contains(p.UserId))throw new UnauthorizedAccessException("You do not have access to this dose.");var m=await db.Medicines.SingleOrDefaultAsync(x=>x.Id==d.MedicineId&&x.PatientId==p.Id)??throw new KeyNotFoundException("Medicine not found.");var owner=await db.Users.FindAsync(p.UserId);var tz=owner?.TimeZoneId??"Asia/Kolkata";if(d.Status=="pending"&&DateOnly.FromDateTime(TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow,Zone(tz)).DateTime)==d.Date&&DateTimeOffset.UtcNow>ScheduledAt(d,Zone(tz))){d.Status="missed";d.MissedAt??=DateTimeOffset.UtcNow;}return(d,m,p,tz);}
 static DateTimeOffset ScheduledAt(DoseEvent d,TimeZoneInfo tz){var local=d.Date.ToDateTime(TimeOnly.Parse(d.Time),DateTimeKind.Unspecified);return new DateTimeOffset(local,tz.GetUtcOffset(local));}
 static TimeZoneInfo Zone(string id){try{return TimeZoneInfo.FindSystemTimeZoneById(id);}catch{return TimeZoneInfo.FindSystemTimeZoneById("Asia/Kolkata");}}
 async Task<HashSet<Guid>>AccessibleUserIds(Guid uid){var ids=await db.FamilyMembers.Where(x=>x.UserId==uid&&x.Status=="approved").Join(db.FamilyMembers,a=>a.FamilyId,b=>b.FamilyId,(a,b)=>b.UserId).Distinct().ToListAsync();ids.Add(uid);return ids.ToHashSet();}
 static DoseResponse Map(DoseEvent d,Medicine m,Patient p)=>new(d.Id,m.Id,p.Id.ToString(),p.Name,m.Name,m.Strength,m.Form,m.Condition,d.Time,m.Liquid,m.WithFood,d.Status,d.TakenAt,d.SkipReason,d.RescheduleTo?.ToString("yyyy-MM-dd"),d.ActionedByUserId,null);
 static bool Occurs(Medicine m,DateOnly d){if(d<m.StartDate||(m.PauseStartDate.HasValue&&d>=m.PauseStartDate.Value&&(!m.PauseEndDate.HasValue||d<=m.PauseEndDate.Value)))return false;var diff=d.DayNumber-m.StartDate.DayNumber;if(!m.IsRecurring&&diff!=0)return false;if(m.DurationType!="ongoing"){var days=m.DurationUnit=="weeks"?m.DurationValue*7:m.DurationUnit=="months"?m.DurationValue*30:m.DurationValue;if(diff>=days)return false;}return m.FrequencyPattern switch{"daily"=>true,"everyOtherDay"=>diff%2==0,"specificDays"=>(JsonSerializer.Deserialize<List<string>>(m.SpecificDaysJson)??[]).Contains(d.DayOfWeek.ToString()[..3],StringComparer.OrdinalIgnoreCase),"recurringCycle"=>m.CycleUnit=="weeks"?diff%(Math.Max(1,m.CycleEvery)*7)==0:m.CycleUnit=="months"?d.Day==m.StartDate.Day:diff%Math.Max(1,m.CycleEvery)==0,_=>false};}}
