const BASE=(import.meta.env.VITE_API_URL||"https://health-tracker-app-3tzi.onrender.com/api").replace(/\/$/,"");
export type User={id:string;email:string;displayName:string;timeZoneId?:string;profileImageUrl?:string|null};
export type Patient={id:string;name:string;dob:string|null;conditions:string[];notes:string;relationship?:string;mobile?:string;doctor?:string;medicalHistory?:string;profileImageUrl?:string;userId?:string;ownerName?:string;ownerEmail?:string};
export type FamilyUser={id:string;userId?:string;email:string;displayName:string;status?:string};
export type Family={id:string;name:string;members:FamilyUser[];pending:{id:string;inviteeUserId:string;status:string}[]};
export type Notification={id:string;type:string;title:string;message:string;dataJson:string;isRead:boolean;createdAt:string};
export type Medicine={id:string;name:string;strength:string;form:string;condition:string;frequencyPattern:string;specificDays:string[];cycleEvery:number;cycleUnit:string;times:string[];liquid:string;withFood:boolean;startDate:string;durationType:string;durationValue:number;durationUnit:string;supplyCount:number;refillThreshold:number;isRecurring:boolean;pauseStartDate?:string|null;pauseEndDate?:string|null};
export type Dose={id:string;medicineId:string;patientId:string;patientName:string;medName:string;strength:string;form:string;condition:string;time:string;liquid:string;withFood:boolean;status:string;takenAt?:string|null;skipReason?:string|null;rescheduleTo?:string|null;actionedByUserId?:string|null;actionedByName?:string|null};
export type HistoryRow={id:string;patientId:string;patientName:string;medicineId:string;medicineName:string;time:string;date:string;status:string;takenAt?:string|null;skipReason?:string|null;actionedByUserId?:string|null;actionedByName?:string|null};
async function request<T>(path:string,o:RequestInit={},auth=true):Promise<T>{const h=new Headers(o.headers);h.set("Content-Type","application/json");const t=localStorage.getItem("access_token");if(auth&&t)h.set("Authorization",`Bearer ${t}`);const r=await fetch(BASE+path,{...o,headers:h});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.message||b.title||"Request failed")}return r.status===204?undefined as T:r.json()}
export const api={
 register:(b:any)=>request<{user:User;token:string}>("/auth/register",{method:"POST",body:JSON.stringify(b)},false),login:(b:any)=>request<{user:User;token:string}>("/auth/login",{method:"POST",body:JSON.stringify(b)},false),me:()=>request<User>("/auth/me"),
 getPatient:()=>request<Patient>("/patient"),getPatients:()=>request<Patient[]>("/patient/all"),savePatient:(b:any,id?:string)=>request<Patient>(id?"/patient/"+id:"/patient",{method:"PUT",body:JSON.stringify(b)}),createPatient:(b:any)=>request<Patient>("/patient",{method:"POST",body:JSON.stringify(b)}),
 updateProfile:(b:any)=>request<User>("/account/profile",{method:"PUT",body:JSON.stringify(b)}),getMedicines:(patientId?:string)=>request<Medicine[]>(patientId?"/medicines?patientId="+patientId:"/medicines"),createMedicine:(b:any,patientId?:string)=>request<Medicine>(patientId?"/medicines?patientId="+patientId:"/medicines",{method:"POST",body:JSON.stringify(b)}),updateMedicine:(id:string,b:any,patientId?:string)=>request<Medicine>("/medicines/"+id+(patientId?"?patientId="+patientId:""),{method:"PUT",body:JSON.stringify(b)}),deleteMedicine:(id:string,patientId?:string)=>request<void>("/medicines/"+id+(patientId?"?patientId="+patientId:""),{method:"DELETE"}),
 getDoses:(d:string,p?:string)=>request<Dose[]>("/doses?date="+d+(p?"&patientId="+p:"")),take:(id:string)=>request<Dose>("/doses/"+id+"/taken",{method:"POST"}),skip:(id:string,reason:string)=>request<Dose>("/doses/"+id+"/skip",{method:"POST",body:JSON.stringify({reason})}),
 familySearch:(q:string)=>request<FamilyUser[]>("/family/search?q="+encodeURIComponent(q)),getFamily:()=>request<Family[]>("/family"),createFamily:(name:string)=>request<any>("/family",{method:"POST",body:JSON.stringify({name})}),inviteFamilyMember:(userId:string)=>request<any>("/family/invite",{method:"POST",body:JSON.stringify({userId})}),getNotifications:()=>request<Notification[]>("/notifications"),readNotification:(id:string)=>request<any>("/notifications/"+id+"/read",{method:"POST"}),respondFamilyInvite:(id:string,accept:boolean)=>request<any>("/family/invites/"+id+"/respond",{method:"POST",body:JSON.stringify({accept})}),
 getHistory:(q:string)=>request<HistoryRow[]>("/history"+q),pauseMedicine:(id:string,startDate:string,endDate?:string)=>request<any>("/medicine-actions/"+id+"/pause",{method:"POST",body:JSON.stringify({startDate,endDate:endDate||null})}),resumeMedicine:(id:string)=>request<any>("/medicine-actions/"+id+"/resume",{method:"POST"}),
 getNotificationSettings:()=>request<any>("/notifications/settings"),saveNotificationSettings:(b:any)=>request<any>("/notifications/settings",{method:"PUT",body:JSON.stringify(b)}),subscribePush:(b:any)=>request<any>("/notifications/push/subscribe",{method:"POST",body:JSON.stringify(b)}),
 forgotPassword:(email:string)=>request<any>("/password/forgot",{method:"POST",body:JSON.stringify({email})},false),resetPassword:(token:string,newPassword:string)=>request<any>("/password/reset",{method:"POST",body:JSON.stringify({token,newPassword})},false)
};
export async function enablePush(vapidPublicKey:string){if(!("serviceWorker"in navigator)||!("PushManager"in window))throw new Error("Push notifications are not supported by this browser.");const reg=await navigator.serviceWorker.register("/sw.js");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Notification permission was not granted.");let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(vapidPublicKey)});const json=sub.toJSON();await api.subscribePush({endpoint:json.endpoint,p256dh:json.keys?.p256dh,auth:json.keys?.auth});return true}
function base64ToBytes(s:string){const pad="=".repeat((4-s.length%4)%4);const raw=atob((s+pad).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
