using System.Security.Claims;using System.Text.Json;using HealthTracker.Api.Contracts;using HealthTracker.Api.Data;using HealthTracker.Api.Models;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace HealthTracker.Api.Controllers;
[Authorize][ApiController][Route("api/family")]
public class FamilyController(AppDbContext db):ControllerBase{
 Guid U=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [HttpGet("search")]public async Task<IActionResult>Search([FromQuery]string q=""){q=q.Trim();if(q.Length<2)return Ok(Array.Empty<object>());return Ok(await db.Users.Where(x=>x.Id!=U&&(x.Email.Contains(q)||x.DisplayName.Contains(q))).OrderBy(x=>x.DisplayName).Take(20).Select(x=>new{x.Id,x.Email,x.DisplayName}).ToListAsync());}
 [HttpGet("notifications")]public async Task<IActionResult>Notifications(){return Ok(await db.Notifications.Where(x=>x.UserId==U).OrderByDescending(x=>x.CreatedAt).Take(50).Select(x=>new{x.Id,x.Type,x.Title,x.Message,x.DataJson,x.IsRead,x.CreatedAt}).ToListAsync());}
 [HttpPost("notifications/{id:guid}/read")]public async Task<IActionResult>Read(Guid id){var n=await db.Notifications.SingleOrDefaultAsync(x=>x.Id==id&&x.UserId==U);if(n is null)return NotFound();n.IsRead=true;await db.SaveChangesAsync();return Ok(n);}
 [HttpPost]public async Task<IActionResult>Create(FamilyCreateRequest r){if(string.IsNullOrWhiteSpace(r.Name))return BadRequest(new{message="Family name is required."});if(await db.FamilyMembers.AnyAsync(x=>x.UserId==U&&x.Status=="approved"))return Conflict(new{message="You are already in a family."});var f=new Family{Name=r.Name.Trim(),OwnerUserId=U};db.Families.Add(f);db.FamilyMembers.Add(new FamilyMember{FamilyId=f.Id,UserId=U});await db.SaveChangesAsync();return Ok(new{f.Id,f.Name});}
 [HttpPost("invite")]public async Task<IActionResult>Invite(FamilyInviteRequest r){var f=await db.Families.SingleOrDefaultAsync(x=>x.OwnerUserId==U);if(f is null)return BadRequest(new{message="Create a family first."});var target=await db.Users.FindAsync(r.UserId);if(target is null||target.Id==U)return NotFound(new{message="User not found."});if(await db.FamilyMembers.AnyAsync(x=>x.FamilyId==f.Id&&x.UserId==target.Id&&x.Status=="approved"))return Conflict(new{message="User already belongs to this family."});if(await db.FamilyInvites.AnyAsync(x=>x.FamilyId==f.Id&&x.InviteeUserId==target.Id&&x.Status=="pending"))return Conflict(new{message="Invitation already pending."});var inv=new FamilyInvite{FamilyId=f.Id,InviterUserId=U,InviteeUserId=target.Id};db.FamilyInvites.Add(inv);var me=await db.Users.FindAsync(U);db.Notifications.Add(new AppNotification{UserId=target.Id,Title="Family invitation",Message=$"{me?.DisplayName??"A user"} invited you to join {f.Name}.",DataJson=JsonSerializer.Serialize(new{inviteId=inv.Id,familyId=f.Id})});await db.SaveChangesAsync();return Ok(new{inv.Id,Status=inv.Status});}
 [HttpPost("invites/{id:guid}/respond")]public async Task<IActionResult>Respond(Guid id,FamilyInviteResponse r){var inv=await db.FamilyInvites.SingleOrDefaultAsync(x=>x.Id==id&&x.InviteeUserId==U);if(inv is null)return NotFound();if(inv.Status!="pending")return Conflict(new{message="Invitation already handled."});inv.Status=r.Accept?"approved":"rejected";if(r.Accept)db.FamilyMembers.Add(new FamilyMember{FamilyId=inv.FamilyId,UserId=U});var n=await db.Notifications.Where(x=>x.UserId==U&&x.DataJson.Contains(id.ToString())).FirstOrDefaultAsync();if(n is not null)n.IsRead=true;await db.SaveChangesAsync();return Ok(new{status=inv.Status});}
 [HttpGet]public async Task<IActionResult>Get(){var ids=await db.FamilyMembers.Where(x=>x.UserId==U&&x.Status=="approved").Select(x=>x.FamilyId).ToListAsync();var fams=await db.Families.Where(x=>ids.Contains(x.Id)).ToListAsync();var members=await db.FamilyMembers.Where(x=>ids.Contains(x.FamilyId)&&x.Status=="approved").ToListAsync();var users=await db.Users.Where(x=>members.Select(m=>m.UserId).Contains(x.Id)).ToListAsync();var pending=await db.FamilyInvites.Where(x=>x.InviterUserId==U&&x.Status=="pending").ToListAsync();return Ok(fams.Select(f=>new{f.Id,f.Name,Members=members.Where(m=>m.FamilyId==f.Id).Select(m=>{var u=users.First(z=>z.Id==m.UserId);return new{m.Id,UserId=u.Id,u.Email,u.DisplayName};}),Pending=pending.Where(i=>i.FamilyId==f.Id).Select(i=>new{i.Id,i.InviteeUserId,i.Status})}));}
}